
name: Send Daum Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0-4'  # 한국시간 오전 8시 (UTC 23시, 월~금)

jobs:
  run-daum-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install beautifulsoup4
          pip install python-telegram-bot==13.15

      - name: Run Daum Report Script
        run: python send_daum_selenium_report.py
