
name: send-daum-selenium-report

on:
  schedule:
    - cron: '0 23 * * *'  # 한국시간 오전 8시 (UTC 기준 23시)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        pip install selenium beautifulsoup4 python-telegram-bot==13.15

    - name: Run Daum Report Script
      run: python send_daum_selenium_report.py
